### ISSUE TITLE
Agent v3.0.0 docker image crashing

### ISSUE THREAD

**Issue by willholley** [logdna/logdna-agent-v2#59] opened 2020-12-21 17:31 UTC
We're noticing that the agent v3.0.0 image is starting but regularly crashing. 

The only error I can see in the logs (obtained using `kubectl logs --previous`) prior to the crash has the pattern:

```
[2020-12-21T17:22:01Z INFO  fs::cache] unwatching "/var/log/containers/sysdig-agent-89cmp_sysdig_sysdig-agent-f39d0ce5b9410a5b560fc067b635541567266a5d83ed5a6fe84253af17ebf053.log"
[2020-12-21T17:22:01Z ERROR fs::tail] can't wrap up deleted symlink - pointed to file / directory doesn't exist: "/var/log/containers/sysdig-agent-89cmp_sysdig_sysdig-agent-f39d0ce5b9410a5b560fc067b635541567266a5d83ed5a6fe84253af17ebf053.log"
[2020-12-21T17:22:01Z INFO  fs::cache] unwatching "/var/data/kubeletlogs/sysdig_sysdig-agent-89cmp_612bf82a-2ed1-4d9a-aa21-a6521901e288/sysdig-agent-kmodule/0.log"
[2020-12-21T17:22:01Z INFO  fs::cache] unwatching "/var/log/containers/sysdig-agent-89cmp_sysdig_sysdig-agent-kmodule-45b85a88be4f33a6a6a8d32d534940aaa6e603b29b61f0bde068f1299aa687f2.log"
[2020-12-21T17:22:01Z ERROR fs::tail] can't wrap up deleted symlink - pointed to file / directory doesn't exist: "/var/log/containers/sysdig-agent-89cmp_sysdig_sysdig-agent-kmodule-45b85a88be4f33a6a6a8d32d534940aaa6e603b29b61f0bde068f1299aa687f2.log"
[2020-12-21T17:22:05Z INFO  fs::cache] unwatching "/var/data/kubeletlogs/fdbcore-perf_c-fdbcore-perf-replication-7b95fbdfd7-wkkft_60322824-19c0-492a-9351-12afc073cf05/db/79.log"
```

It seems that the container then exited - `kubectl describe pod` shows:

```
Events:
  Type     Reason   Age                     From     Message
  ----     ------   ----                    ----     -------
  Warning  BackOff  91s (x1416 over 6h54m)  kubelet  Back-off restarting failed container
```

Do you have any suggestions as to what might be wrong/how to debug further?

**Comment by willholley** [comment] 2020-12-21 17:36
also noting this is only occuring on a subset of pods:
```
kubectl get pods -n logdna
NAME                 READY   STATUS             RESTARTS   AGE
logdna-agent-279xj   1/1     Running            1          5d1h
logdna-agent-4c854   1/1     Running            0          5d1h
logdna-agent-598l9   1/1     Running            0          5d1h
logdna-agent-5dlvr   0/1     CrashLoopBackOff   87         5d1h
logdna-agent-5psz7   1/1     Running            4          5d1h
logdna-agent-6pt8z   1/1     Running            1          5d1h
logdna-agent-9q874   1/1     Running            10         5d1h
logdna-agent-c7brx   1/1     Running            4          5d1h
logdna-agent-ddslm   1/1     Running            0          5d1h
logdna-agent-dghkj   1/1     Running            0          5d1h
logdna-agent-dq97j   1/1     Running            0          5d1h
logdna-agent-fvzkr   1/1     Running            4          5d1h
logdna-agent-g8m2j   1/1     Running            0          5d1h
logdna-agent-h992g   1/1     Running            1          5d1h
logdna-agent-kpkdj   1/1     Running            21         5d1h
logdna-agent-l9777   1/1     Running            1          5d1h
logdna-agent-qq2cc   1/1     Running            16         5d1h
logdna-agent-qvjhk   1/1     Running            1          5d1h
logdna-agent-r82vs   1/1     Running            1          5d1h
logdna-agent-r8tnk   1/1     Running            0          5d1h
logdna-agent-rplzd   1/1     Running            1          5d1h
logdna-agent-sh2fn   1/1     Running            1          5d1h
logdna-agent-sl5gp   0/1     CrashLoopBackOff   78         5d1h
logdna-agent-thkst   1/1     Running            4          5d1h
logdna-agent-tqrcz   1/1     Running            2          5d1h
logdna-agent-tvctj   1/1     Running            7          5d1h
logdna-agent-vfnwv   0/1     CrashLoopBackOff   80         5d1h
logdna-agent-vtrxc   1/1     Running            406        5d1h
logdna-agent-z8r2m   1/1     Running            1          5d1h
logdna-agent-zw575   1/1     Running            1          5d1h
```

**Comment by c-nixon** [comment] 2020-12-21 17:38
Hi @willholley thanks for the report. I'll look into this now.

Is there another pod running on each of those nodes? It might be a strange interaction that we havn't seen before in testing.

**Comment by c-nixon** [comment] 2020-12-21 17:45
My _guess_ is that sysdig creates a dangling symlink and we're not handling that correctly. You may be able to add an exclusion rule until we have a fix.

**Comment by willholley** [comment] 2020-12-21 18:19
thanks @c-nixon. Looking at the errors logged across all pods it doesn't appear to be limited to only Sysdig:


```
Dec 21 18:16:41 logdna-agent-l9777 logdna-agent ERROR fs::tail] unable to stat "/var/log/containers/ccmd-1608573840-skp6t_ccmd-sapitest_ccmd-b95d3f03f745fbd5ea2ffff8fdd3f1a2abe172d1b0834a8dc4b27615864b0a85.log": Os { code: 9, kind: Other, message: "Bad file descriptor" }
Dec 21 18:16:41 logdna-agent-l9777 logdna-agent ERROR fs::tail] can't wrap up deleted symlink - pointed to file / directory doesn't exist: "/var/log/containers/ccmd-1608573840-skp6t_ccmd-sapitest_ccmd-b95d3f03f745fbd5ea2ffff8fdd3f1a2abe172d1b0834a8dc4b27615864b0a85.log"
Dec 21 18:16:43 logdna-agent-4blsd logdna-agent ERROR fs::tail] can't wrap up deleted symlink - pointed to file / directory doesn't exist: "/var/log/containers/ccmd-1608573840-vgvkd_ccmd_ccmd-4ef0ae1dccd5321509899d813dc5c9a483d3bab7ff849ed379392ddc4f536c4c.log"
Dec 21 18:16:50 logdna-agent-6bwpx logdna-agent ERROR fs::tail] unable to stat "/var/log/containers/chassis2-67855b879d-2fmr5_chassis-production-global_istio-proxy-862a6f7275631aa3911b54bf5f9cb7770bdb33b9f1bb3b41ce0f54025b137ffd.log": Os { code: 9, kind: Other, message: "Bad file descriptor" }
Dec 21 18:17:09 logdna-agent-ztfcv logdna-agent ERROR fs::tail] unable to stat "/var/log/containers/chassis2-67855b879d-tw4g4_chassis-production-global_istio-proxy-5692c018cd5e83b286937660e4bcb809a3ae2dd66cb5f5bd8475af705b854f86.log": Os { code: 9, kind: Other, message: "Bad file descriptor" }
Dec 21 18:17:33 logdna-agent-mfckf logdna-agent ERROR fs::tail] unable to stat "/var/log/containers/chassis2-67855b879d-wq5f2_chassis-production-global_istio-proxy-a53130d2d506402996a5b2b6c6fd13f49520aff3a890de375f5871255cdf2498.log": Os { code: 9, kind: Other, message: "Bad file descriptor" }
Dec 21 18:17:41 logdna-agent-l9777 logdna-agent ERROR fs::tail] can't wrap up deleted symlink - pointed to file / directory doesn't exist: "/var/log/containers/ccmd-1608573900-h42tz_ccmd-sapitest_ccmd-01367b50db01da6ceaeb0bf78d284ba6c41359c10cc2f4fe5bbab32de364613c.log"
Dec 21 18:17:44 logdna-agent-4blsd logdna-agent ERROR fs::tail] can't wrap up deleted symlink - pointed to file / directory doesn't exist: "/var/log/containers/ccmd-1608573900-qrn4b_ccmd_ccmd-8ccddd704848fd91ede9f92b66797d80500150aaf2cc14a3a9ccf15c1a3c048b.log" 
```

**Comment by c-nixon** [comment] 2020-12-21 18:47
Aha, that set looks like a race condition. Our new streaming architecture may be processing delete's more quickly than the old threaded model.

Are the pods in that second set of logs also in a restart loop? Or do they restart and then continue on?

**Comment by willholley** [comment] 2020-12-21 20:37
They don't all appear to be in restart loops e.g. `logdna-agent-l9777` has a lot of `can't wrap up deleted symlink` errors in the log but has only restarted twice in 5 days wheras others are restarting every few minutes.

Looking at the pod state, the interesting part seems to be `exitCode: 139` - I see that exitCode for all the pods that are crashing:

```
lastState:
      terminated:
        containerID: containerd://bb7cd33a319b4f6a794b5f8bbfaf689d78dabbfe3ea1df1fe0037394ca6d45f0
        exitCode: 139
        finishedAt: "2020-12-21T20:30:31Z"
        reason: Error
        startedAt: "2020-12-21T16:31:02Z"
```

**Comment by c-nixon** [comment] 2020-12-21 21:07
Hmm, curiouser and curiouser. Could you add

```
            - name: RUST_BACKTRACE
              value: full
```
to the env section of the agent container

**Comment by willholley** [comment] 2020-12-21 21:34
hmm - log getting any more info I'm afraid:

```
kubectl get pods -n logdna
NAME                 READY   STATUS    RESTARTS   AGE
logdna-agent-26zgq   1/1     Running   0          8m6s
logdna-agent-5kw4t   1/1     Running   2          8m1s
logdna-agent-67qfz   1/1     Running   0          8m3s
logdna-agent-7rhgg   1/1     Running   0          8m3s
logdna-agent-8mcth   1/1     Running   0          8m6s
logdna-agent-8phdx   1/1     Running   0          8m7s
logdna-agent-b87b8   1/1     Running   0          8m6s
logdna-agent-bjwdj   1/1     Running   0          8m5s
logdna-agent-d2gw7   1/1     Running   2          8m7s
logdna-agent-dznqk   1/1     Running   0          8m6s
logdna-agent-f4mfq   1/1     Running   0          8m6s
logdna-agent-fbxbv   1/1     Running   0          8m7s
logdna-agent-fdv27   1/1     Running   0          8m9s
logdna-agent-fp928   1/1     Running   0          8m8s
logdna-agent-h8jqx   1/1     Running   0          8m
logdna-agent-k598d   1/1     Running   0          8m5s
logdna-agent-kn5kb   1/1     Running   0          8m4s
logdna-agent-lsk5k   1/1     Running   0          8m10s
logdna-agent-nwdvs   1/1     Running   0          8m4s
logdna-agent-pzlzh   1/1     Running   0          8m3s
logdna-agent-qvrcx   1/1     Running   0          8m2s
logdna-agent-r6lt6   1/1     Running   0          7m59s
logdna-agent-rlzkh   1/1     Running   0          8m2s
logdna-agent-v47zc   1/1     Running   1          8m8s
logdna-agent-vbkhw   1/1     Running   0          8m
logdna-agent-vghpf   1/1     Running   0          8m6s
logdna-agent-xsw64   1/1     Running   0          8m
```

then picking one pod that's restarted (`logdna-agent-v47zc`):

```
kubectl get pod logdna-agent-v47zc -n logdna -ojson | jq '.status.containerStatuses[].lastState'                                                                                  
{
  "terminated": {
    "containerID": "containerd://a1df945deaccf530172db592b59b19b92e3773eec05f297810911c26e025499a",
    "exitCode": 139,
    "finishedAt": "2020-12-21T21:28:32Z",
    "reason": "Error",
    "startedAt": "2020-12-21T21:23:04Z"
  }
}


kubectl logs -n logdna logdna-agent-v47zc --previous --tail 20
[2020-12-21T21:23:04Z INFO  fs::tail] initialized "/var/log/docker.log" with len 0 offset 0
[2020-12-21T21:23:04Z INFO  fs::tail] initialized "/var/log/cloud-init.log" with offset 117041
[2020-12-21T21:23:04Z INFO  fs::tail] initialized "/var/log/unattended-upgrades/unattended-upgrades-shutdown.log" with len 112 offset 0
[2020-12-21T21:23:04Z INFO  fs::tail] initialized "/var/log/cloud-init-output.log" with len 5944 offset 0
[2020-12-21T21:23:04Z INFO  fs::tail] initialized "/var/log/apport.log" with offset 14409
[2020-12-21T21:23:04Z INFO  fs::tail] initialized "/var/log/sudo.log" with offset 30894
[2020-12-21T21:23:04Z INFO  fs::tail] initialized "/var/log/kern.log" with offset 521873
[2020-12-21T21:23:04Z INFO  fs::tail] initialized "/var/log/firstboot.log" with offset 29017
[2020-12-21T21:23:04Z INFO  fs::tail] initialized "/var/log/syslog" with offset 84618937
[2020-12-21T21:23:04Z INFO  fs::tail] initialized "/var/log/landscape/sysinfo.log" with len 0 offset 0
[2020-12-21T21:23:04Z INFO  fs::tail] initialized "/var/log/apt/history.log" with len 521 offset 0
[2020-12-21T21:23:04Z INFO  fs::tail] initialized "/var/log/apt/term.log" with len 3176 offset 0
[2020-12-21T21:24:04Z INFO  metrics] {"fs":{"events":838,"creates":0,"deletes":0,"writes":838,"lines":988,"bytes":197199,"partial_reads":823},"memory":{"active":22769664,"allocated":19258240,"resident":27430912},"ingest":{"requests":179,"throughput":195909,"rate_limits":0,"retries":0},"k8s":{"lines":0,"polls":0,"creates":567,"deletes":1,"events":0,"notifies":0},"journald":{"lines":0,"bytes":0}}
[2020-12-21T21:25:04Z INFO  metrics] {"fs":{"events":864,"creates":0,"deletes":0,"writes":864,"lines":987,"bytes":196337,"partial_reads":848},"memory":{"active":22769664,"allocated":19258072,"resident":27430912},"ingest":{"requests":179,"throughput":195501,"rate_limits":0,"retries":0},"k8s":{"lines":0,"polls":0,"creates":10,"deletes":1,"events":0,"notifies":0},"journald":{"lines":0,"bytes":0}}
[2020-12-21T21:26:04Z INFO  metrics] {"fs":{"events":884,"creates":0,"deletes":0,"writes":884,"lines":1021,"bytes":201915,"partial_reads":866},"memory":{"active":22753280,"allocated":19253592,"resident":27414528},"ingest":{"requests":175,"throughput":200595,"rate_limits":0,"retries":0},"k8s":{"lines":0,"polls":0,"creates":15,"deletes":1,"events":0,"notifies":0},"journald":{"lines":0,"bytes":0}}
[2020-12-21T21:27:04Z INFO  metrics] {"fs":{"events":819,"creates":0,"deletes":0,"writes":819,"lines":959,"bytes":192328,"partial_reads":808},"memory":{"active":22704128,"allocated":19230016,"resident":27365376},"ingest":{"requests":176,"throughput":191668,"rate_limits":0,"retries":0},"k8s":{"lines":0,"polls":0,"creates":10,"deletes":1,"events":0,"notifies":0},"journald":{"lines":0,"bytes":0}}
[2020-12-21T21:28:04Z INFO  metrics] {"fs":{"events":846,"creates":0,"deletes":0,"writes":846,"lines":957,"bytes":190081,"partial_reads":833},"memory":{"active":22732800,"allocated":19256288,"resident":27394048},"ingest":{"requests":185,"throughput":188828,"rate_limits":0,"retries":0},"k8s":{"lines":0,"polls":0,"creates":20,"deletes":1,"events":0,"notifies":0},"journald":{"lines":0,"bytes":0}}
[2020-12-21T21:28:09Z INFO  fs::cache] watching "/var/data/kubeletlogs/fdbcore-perf_c-fdbcore-perf-replication-7b95fbdfd7-hb65l_bccf49c9-0413-4b0f-9382-c11a61bb3036/db/125.log"
[2020-12-21T21:28:09Z INFO  fs::cache] watching "/var/log/containers/c-fdbcore-perf-replication-7b95fbdfd7-hb65l_fdbcore-perf_db-2e245e4355456018f68e27e914d877642ce71ff25919b24338f2a3220fb77cbc.log"
[2020-12-21T21:28:32Z INFO  fs::cache] unwatching "/var/data/kubeletlogs/fdbcore-perf_c-fdbcore-perf-replication-7b95fbdfd7-hb65l_bccf49c9-0413-4b0f-9382-c11a61bb3036/db/124.log"

``` 




```

**Comment by c-nixon** [comment] 2020-12-21 21:55
Thanks! That massively narrows down where I need to look. Looks like it's something filesystem related in the fs cache unwatch logic during log rotation. It's possible we're trying to read from a closed filehandle or perform some other illegal operation.

Now that you have the RUST_BACKTRACE env var set you may get a stack trace from one of the other agents, if you do see one it would be really useful while in reproducing it

**Comment by jorgebay** [comment] 2021-01-04 16:13
Good news! We were able to reproduce it here: https://github.com/logdna/logdna-agent-v2/pull/63/commits/8e3f17b6d227c6e87ff03a65c1fb86d7516d27fe

It looks like the underlying issue is related to how our `fs` module uses pointers to files/directories and it's surfaced now more frequently thanks to event streaming deleting them more quickly, as @c-nixon mentioned.

We are looking into fixing it, it's going to take some refactoring of the fs module to use `RC`/`Arc`/`Weak`.

Thanks again @willholley for all the info.

**Comment by willholley** [comment] 2021-01-04 16:16
thanks for the update @jorgebay - that's great to hear.

**Comment by c-nixon** [comment] 2021-01-12 13:05
Hi @willholley, this should be fixed in the 3.0.1 patch release, Github "helpfully" closed this issue because I referenced it in the PR. Can you confirm if you're still seeing the issue with the newer build?

**Comment by willholley** [comment] 2021-01-12 17:02
thanks @c-nixon - looking good now. I haven't observed any crashes since we deployed the new image today.

**Comment by c-nixon** [comment] 2021-01-14 12:17
Thanks!

**Closed by c-nixon** 2021-01-14 12:17 UTC
