### ISSUE TITLE
Latest v3 Docker image fails to launch

### ISSUE THREAD

**Issue by jalenplayvs** [logdna/logdna-agent-v2#57] opened 2020-12-18 19:41 UTC
Launching latest logdna/logdna-agent:3 from DockerHub

Prints the following to stderr and exits immediately, both locally and in AWS ECS:
```
$ docker run -it logdna/logdna-agent:3   
standard_init_linux.go:219: exec user process caused: operation not permitted
```
If I inspect the image locally, it appears that there is only one file on it:
```
$ docker run -it logdna/logdna-agent:3 sh                      
sh-4.4# ls -alh
total 13M
drwxrwxrwx 1 root root 4.0K Dec 15 13:04 .
drwxr-xr-x 1 root root 4.0K Dec 18 19:30 ..
-rwxrwxrwx 1 root root  13M Dec 15 13:04 logdna-agent
sh-4.4# ./logdna-agent 
sh: ./logdna-agent: Operation not permitted
```

**Comment by jalenplayvs** [comment] 2020-12-18 19:44
Looked into downgrading to `logdna/logdna-agent:2`, it also has one file on the iimage, but attempts to execute the binary do not fail with 'Operation not permitted'

**Comment by jorgebay** [comment] 2020-12-21 10:33
I was able to reproduce it.

It looks like it occurred w/ beta versions of 2.2 as well.

This works:

```bash
docker run -it -e LOGDNA_INGESTION_KEY logdna/logdna-agent:2.2
```

This exists w/ "operation not permitted":

```bash
docker run -it -e LOGDNA_INGESTION_KEY logdna/logdna-agent:2.2.0-beta.12
```

**Comment by jorgebay** [comment] 2020-12-21 11:36
The issue is related to the capabilities of the process, the agent is currently using `cap_dac_read_search`.

Changing it to `cap_dac_override` does the trick.

```bash
$ docker run -it -e LOGDNA_INGESTION_KEY logdna/logdna-agent:3 sh
sh-4.4# setcap "cap_dac_override+eip" ./logdna-agent
sh-4.4# ./logdna-agent 
```

**Comment by jorgebay** [comment] 2020-12-21 11:36
I'll submit a PR to update the image.

**Comment by c-nixon** [comment] 2020-12-21 11:43
@jalenplayvs Did you update to the new yamls? The error you're seeing suggests your daemonset isn't configured to allow CAP_DAC_READ.

The agent 3.0 yamls have it set like this : https://github.com/logdna/logdna-agent-v2/blob/79671a727b1f305e596f72995fdf39f776b46358/k8s/agent-resources.yaml#L107

**Comment by jalenplayvs** [comment] 2020-12-21 23:10
> @jalenplayvs Did you update to the new yamls? The error you're seeing suggests your daemonset isn't configured to allow CAP_DAC_READ_SEARCH.

Was not running it in Kubernetes, was running in just plain Docker and also AWS ECS Fargate.  I know the Dockerhub page says "LogDNA Agent for Kubernetes", but as far as I can tell it's the exact same logdna-agent that runs in any other context, correct?  Was able to get the `logdna/logdna-agent:1` image running in my environment and shipping logs.  IMHO it would be a mistake to only make a single image for logdna-agent that only works in Kubernetes with specific API object configurations.  We want to be able to run local dev environments (using docker-compose or similar) that mimic production as closely as possible.

However, the current way I am using this image is not ideal, or very "cloud native".  I had been evaluating the possibility of doing the simplest possible lift-n-shift of what we have in EC2 into ECS, without rearchitecting how we log.  We are now going to evaluate how much effort it would be to use other means of ingesting logs from ECS tasks into LogDNA before proceeding with this solution.  So maybe we do not even do this in the end.  I'm open to any suggestions of better ways to do this.

**Comment by jakedipity** [comment] 2020-12-21 23:55
The current latest version of the agent should be okay to run outside of Kubernetes. It does make the assumption the API is reachable and you'll get some warnings / errors on startup, but it shouldn't terminate and should run as expected.

The expected capability isn't set by docker by default so we need to set that manually:
```
docker run -it --cap-add DAC_READ_SEARCH -e LOGDNA_INGESTION_KEY=password logdna/logdna-agent:3
```

**Comment by jalenplayvs** [comment] 2020-12-22 01:26
Cool.  Looks like ECS supports setting that:
https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_KernelCapabilities.html

I will try to port it back to `:3` this week.
Might be good to make that requirement more visible in places like Dockerhub and maybe a section in the `README.md`.

**Comment by jakedipity** [comment] 2021-05-03 17:33
This issue has been sufficiently addressed, closing for now.

**Closed by jakedipity** 2021-05-03 17:33 UTC
